# 3.1 Creating a Data Frame

In [32]:
import pandas as pd

In [33]:
dataframe = pd.DataFrame()

# Add columns
dataframe['Name'] = ['Jacky Jackson', 'Steven Stevenson']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]


# Show DataFrame
dataframe

               Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False

In [34]:
# Create row
new_person = pd.Series(['Molly Mooney', 40, True], index=['Name','Age','Driver'])
new_person

Name      Molly Mooney
Age                 40
Driver            True
dtype: object

In [35]:
# Append row
dataframe = pd.concat(
    [dataframe, pd.DataFrame([new_person])],
    ignore_index=True
)

In [36]:
dataframe

               Name  Age  Driver
0     Jacky Jackson   38    True
1  Steven Stevenson   25   False
2      Molly Mooney   40    True

# 3.2 Describing the Data

In [37]:
titanic_data_set_url = "https://raw.githubusercontent.com/chrisalbon/sim_data/refs/heads/main/titanic.csv"

In [38]:
df = pd.read_csv(titanic_data_set_url)

In [39]:
df

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

In [40]:
df.describe()

              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 3.3 Navigating DataFrames

In [41]:
df.iloc[:] # all

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

In [42]:
df.iloc[1: 4]

,Name,PClass,Age,Sex,Survived,SexCode
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1

In [43]:
df.set_index(df['Name']) 
# now if you notice one number col is remove
# see above and below df

,Name,PClass,Age,Sex,Survived,SexCode
Name,,,,,,
"Allen, Miss Elisabeth Walton","Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
"Allison, Miss Helen Loraine","Allison, Miss Helen Loraine",1st,2.00,female,0,1
"Allison, Mr Hudson Joshua Creighton","Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
"Allison, Mrs Hudson JC (Bessie Waldo Daniels)","Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
"Allison, Master Hudson Trevor","Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
"Zakarian, Mr Artun","Zakarian, Mr Artun",3rd,27.00,male,0,0
"Zakarian, Mr Maprieder","Zakarian, Mr Maprieder",3rd,26.00,male,0,0
"Zenni, Mr Philip","Zenni, Mr Philip",3rd,22.00,male,0,0
"Lievens, Mr Rene","Lievens, Mr Rene",3rd,24.00,male,0,0
"Zimmerman, Leo","Zimmerman, Leo",3rd,29.00,male,0,0

# 3.4 Selecting Rows Based on Conditionals

In [44]:
df[df['Sex'] == 'female'].head(2)

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [45]:
df[(df['Sex'] == 'female') & (df['Age'] >= 65)]

,Name,PClass,Age,Sex,Survived,SexCode
73,"Crosby, Mrs Edward Gifford (Catherine Elizabet...",1st,69.0,female,1,1

# 3.5 Replacing Values

In [46]:
df['Sex'].replace(['female', 'male'], ['Women', 'Men']).sample(3)

242      Men
969      Men
905    Women
Name: Sex, dtype: str

# 3.6 Renaming Columns

In [47]:
df.rename(columns={'PClass': 'Passenger Class', 'Sex': 'Gender'}).sample(3)

                     Name Passenger Class   Age Gender  Survived  SexCode
160      Lewy, Mr Ervin G             1st   NaN   male         0        0
1279  Vartunian, Mr David             3rd  22.0   male         1        0
1106      Pasic, Mr Jakob             3rd   NaN   male         0        0

# 3.7 Finding the Minimum, Maximum, Sum, Average, and Count

In [48]:
df = pd.read_csv(titanic_data_set_url)
df

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

In [49]:

# Calculate statistics
print('Maximum:', df['Age'].max())
print('Minimum:', df['Age'].min())
print('Mean:', df['Age'].mean())
print('Sum:', df['Age'].sum())
print('Count:', df['Age'].count())

Maximum: 71.0
Minimum: 0.17
Mean: 30.397989417989418
Sum: 22980.88
Count: 756

In [50]:
df.count()

Name        1313
PClass      1313
Age          756
Sex         1313
Survived    1313
SexCode     1313
dtype: int64

# 3.8 Finding Unique Values

In [51]:
df['Sex'].unique()

<StringArray>
['female', 'male']
Length: 2, dtype: str

In [52]:
df['Sex'].value_counts()

Sex
male      851
female    462
Name: count, dtype: int64

# 3.9 Handling Missing Values

In [53]:
df[df['Age'].isnull()].sample(3)

                                 Name PClass  Age     Sex  Survived  SexCode
1300            Wiseman, Mr Phillippe    3rd  NaN    male         0        0
1001                McCoy, Miss Alice    3rd  NaN  female         0        1
1036  Moubarek, Master William George    3rd  NaN    male         0        0

In [54]:
import numpy as np

In [55]:
df['sex_2'] = df['Sex'].replace('male', np.nan)

In [56]:
df['sex_2']

0       female
1       female
2          NaN
3       female
4          NaN
         ...
1308       NaN
1309       NaN
1310       NaN
1311       NaN
1312       NaN
Name: sex_2, Length: 1313, dtype: str

In [57]:
# Load data, set missing values
dataframe = pd.read_csv(titanic_data_set_url, na_values=[np.nan, 'NONE', -999])

In [58]:
dataframe

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

# 3.10 Deleting a Column

In [62]:
df.drop(['Age', 'sex_2'], axis=1).sample(3)

                             Name PClass   Sex  Survived  SexCode
1071  Nosworthy, Mr Richard Cater    3rd  male         0        0
539              Reeves, Mr David    2nd  male         0        0
813          Gallagher, Mr Martin    3rd  male         0        0

# 3.11 Deleting a Row

In [63]:
df[df['Name'] != 'Allison, Miss Helen Loraine'].head(2)

,Name,PClass,Age,Sex,Survived,SexCode,sex_2
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1,female
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0,NaN

# 3.12 Dropping Duplicate Rows

In [64]:
df.drop_duplicates()

,Name,PClass,Age,Sex,Survived,SexCode,sex_2
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1,female
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1,female
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0,NaN
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1,female
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0,NaN
...,...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0,NaN
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0,NaN
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0,NaN
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0,NaN
1312,"Zimmerman, Leo",3rd,29.00,male,0,0,NaN

# 3.13 Grouping Rows by Values

In [69]:
df.groupby('Sex')['Age'].mean()

Sex
female    29.396424
male      31.014338
Name: Age, dtype: float64

In [70]:
df.groupby('Sex')['Survived'].mean()

Sex
female    0.666667
male      0.166863
Name: Survived, dtype: float64

# 3.14 Grouping Rows by Time

In [71]:
import numpy as np

In [89]:
time_index = pd.date_range('06/06/2017', periods=100_000, freq='30s')

In [90]:
df = pd.DataFrame(index=time_index)

In [91]:
df

Empty DataFrame
Columns: []
Index: [2017-06-06 00:00:00, 2017-06-06 00:00:30, 2017-06-06 00:01:00, 2017-06-06 00:01:30, 2017-06-06 00:02:00, 2017-06-06 00:02:30, 2017-06-06 00:03:00, 2017-06-06 00:03:30, 2017-06-06 00:04:00, 2017-06-06 00:04:30, 2017-06-06 00:05:00, 2017-06-06 00:05:30, 2017-06-06 00:06:00, 2017-06-06 00:06:30, 2017-06-06 00:07:00, 2017-06-06 00:07:30, 2017-06-06 00:08:00, 2017-06-06 00:08:30, 2017-06-06 00:09:00, 2017-06-06 00:09:30, 2017-06-06 00:10:00, 2017-06-06 00:10:30, 2017-06-06 00:11:00, 2017-06-06 00:11:30, 2017-06-06 00:12:00, 2017-06-06 00:12:30, 2017-06-06 00:13:00, 2017-06-06 00:13:30, 2017-06-06 00:14:00, 2017-06-06 00:14:30, 2017-06-06 00:15:00, 2017-06-06 00:15:30, 2017-06-06 00:16:00, 2017-06-06 00:16:30, 2017-06-06 00:17:00, 2017-06-06 00:17:30, 2017-06-06 00:18:00, 2017-06-06 00:18:30, 2017-06-06 00:19:00, 2017-06-06 00:19:30, 2017-06-06 00:20:00, 2017-06-06 00:20:30, 2017-06-06 00:21:00, 2017-06-06 00:21:30, 2017-06-06 00:22:00, 2017-06-06 00:22:30, 2017-06-06 00:23:00, 2017-06-06 00:23:30, 2017-06-06 00:24:00, 2017-06-06 00:24:30, 2017-06-06 00:25:00, 2017-06-06 00:25:30, 2017-06-06 00:26:00, 2017-06-06 00:26:30, 2017-06-06 00:27:00, 2017-06-06 00:27:30, 2017-06-06 00:28:00, 2017-06-06 00:28:30, 2017-06-06 00:29:00, 2017-06-06 00:29:30, 2017-06-06 00:30:00, 2017-06-06 00:30:30, 2017-06-06 00:31:00, 2017-06-06 00:31:30, 2017-06-06 00:32:00, 2017-06-06 00:32:30, 2017-06-06 00:33:00, 2017-06-06 00:33:30, 2017-06-06 00:34:00, 2017-06-06 00:34:30, 2017-06-06 00:35:00, 2017-06-06 00:35:30, 2017-06-06 00:36:00, 2017-06-06 00:36:30, 2017-06-06 00:37:00, 2017-06-06 00:37:30, 2017-06-06 00:38:00, 2017-06-06 00:38:30, 2017-06-06 00:39:00, 2017-06-06 00:39:30, 2017-06-06 00:40:00, 2017-06-06 00:40:30, 2017-06-06 00:41:00, 2017-06-06 00:41:30, 2017-06-06 00:42:00, 2017-06-06 00:42:30, 2017-06-06 00:43:00, 2017-06-06 00:43:30, 2017-06-06 00:44:00, 2017-06-06 00:44:30, 2017-06-06 00:45:00, 2017-06-06 00:45:30, 2017-06-06 00:46:00, 2017-06-06 00:46:30, 2017-06-06 00:47:00, 2017-06-06 00:47:30, 2017-06-06 00:48:00, 2017-06-06 00:48:30, 2017-06-06 00:49:00, 2017-06-06 00:49:30, ...]

[100000 rows x 0 columns]

In [92]:
df['sale_amount'] = np.random.randint(1, 200, 100_000)

In [93]:
df

                     sale_amount
2017-06-06 00:00:00          128
2017-06-06 00:00:30          173
2017-06-06 00:01:00           75
2017-06-06 00:01:30           59
2017-06-06 00:02:00          157
...                          ...
2017-07-10 17:17:30           48
2017-07-10 17:18:00          198
2017-07-10 17:18:30           10
2017-07-10 17:19:00          103
2017-07-10 17:19:30           62

[100000 rows x 1 columns]

In [94]:
df.resample('W').sum()

            sale_amount
2017-06-11      1736917
2017-06-18      2010727
2017-06-25      2035581
2017-07-02      2017421
2017-07-09      1998257
2017-07-16       209337

In [95]:
df.resample('2W').mean()

            sale_amount
2017-06-11   100.516030
2017-06-25   100.354861
2017-07-09    99.595188
2017-07-23   100.642788

# 3.15 Looping Over a Column

In [98]:
tdf = pd.read_csv(titanic_data_set_url)

In [100]:
for name in tdf['Name'][:2]:
    print(name.upper())

ALLEN, MISS ELISABETH WALTON
ALLISON, MISS HELEN LORAINE

# 3.16 Applying a Function Over All Elements in a Column

In [101]:
def make_uppercase(x):
    return x.upper()

In [102]:
tdf['Name'].apply(make_uppercase)

0                        ALLEN, MISS ELISABETH WALTON
1                         ALLISON, MISS HELEN LORAINE
2                 ALLISON, MR HUDSON JOSHUA CREIGHTON
3       ALLISON, MRS HUDSON JC (BESSIE WALDO DANIELS)
4                       ALLISON, MASTER HUDSON TREVOR
                            ...
1308                               ZAKARIAN, MR ARTUN
1309                           ZAKARIAN, MR MAPRIEDER
1310                                 ZENNI, MR PHILIP
1311                                 LIEVENS, MR RENE
1312                                   ZIMMERMAN, LEO
Name: Name, Length: 1313, dtype: str

# 3.17 Applying a Function to Groups

In [103]:
tdf.groupby('Sex').apply(lambda x: x.count())

        Name  PClass  Age  Survived  SexCode
Sex
female   462     462  288       462      462
male     851     851  468       851      851

# 3.18 Concatenating DataFrames

In [104]:
data_a = {'id': ['1', '2', '3'],
 'first': ['Alex', 'Amy', 'Allen'],
 'last': ['Anderson', 'Ackerman', 'Ali']}
dataframe_a = pd.DataFrame(data_a, columns = ['id', 'first', 'last'])

# Create DataFrame
data_b = {'id': ['4', '5', '6'],
 'first': ['Billy', 'Brian', 'Bran'],
 'last': ['Bonder', 'Black', 'Balwner']}

dataframe_b = pd.DataFrame(data_b, columns = ['id', 'first', 'last'])


# Concatenate DataFrames by rows
pd.concat([dataframe_a, dataframe_b], axis=0)

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
0  4  Billy    Bonder
1  5  Brian     Black
2  6   Bran   Balwner

# 3.19 Merging DataFrames

In [109]:
employee_data = {'employee_id': ['1', '2', '3', '4'],
 'name': ['Amy Jones', 'Allen Keys', 'Alice Bees',
 'Tim Horton']}


dataframe_employees = pd.DataFrame(employee_data, columns = ['employee_id',
 'name'])

dataframe_employees

  employee_id        name
0           1   Amy Jones
1           2  Allen Keys
2           3  Alice Bees
3           4  Tim Horton

In [110]:
# Create DataFrame
sales_data = {'employee_id': ['3', '4', '5', '6'],
 'total_sales': [23456, 2512, 2345, 1455]}

dataframe_sales = pd.DataFrame(sales_data, columns = ['employee_id',
 'total_sales'])

dataframe_sales

  employee_id  total_sales
0           3        23456
1           4         2512
2           5         2345
3           6         1455

In [ ]:
# Merge DataFrames
pd.merge(dataframe_employees, dataframe_sales, on='employee_id')

  employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

In [111]:
pd.merge(
    dataframe_employees,
    dataframe_sales,
    on='employee_id',
    how='outer'
)

  employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0
4           5         NaN       2345.0
5           6         NaN       1455.0

In [112]:
pd.merge(dataframe_employees,
 dataframe_sales,
 left_on='employee_id',
 right_on='employee_id')

  employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512